### ISSUE TITLE
Typo on "Kumpulang"

### ISSUE THREAD

**Issue by iffanmajid** [id-mozilla/pantun-tentang-internet#6]
https://github.com/id-mozilla/pantun-tentang-internet/blob/f0b456a58a55c117eb94091f3a6db3b9c14371fe/index.html#L4
https://github.com/id-mozilla/pantun-tentang-internet/blob/f0b456a58a55c117eb94091f3a6db3b9c14371fe/index.html#L12

**Comment by dikyarga** [comment]
saya mengerjakan ini
